# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  mobile_test:
    docker:
      - image: circleci/node:11

    working_directory: ~/repo/mobile
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-mobile-deps-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-mobile-deps-
      - run: yarn install
      - run: mkdir -p reports/junit/

      - run:
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: yarn test --ci --reporters="jest-junit"

      - save_cache:
          key: v1-mobile-deps-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  api_test:
    working_directory: ~/repo/api
    docker:
      - image: codestar/circleci-scala-sbt-git:scala-2.12.6-sbt-1.1.6
      # specify the version you desire here
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: bikechain


    steps:
      - checkout:
          path: ~/repo
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: sbt "runMain com.bikechain.data.CreateTables"
      # run tests coverage
      - run: sbt coverage test:compile

      - run: sbt coverage test

      - save_cache:
          key: v1-dependencies-{{ checksum "build.sbt" }}
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

      # run tests!
      - run: sbt coverageReport

      - store_test_results:
          path: target/test-reports

      - store_artifacts:
          path: target/scala-2.12/scoverage-report
workflows:
  version: 2
  api_and_mobile:
    jobs:
      - api_test
      - mobile_test
