version: "3.1"

services:
  db:
    image: postgres:10.7
    restart: always
    environment:
      POSTGRES_DB: bikechain
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
